<?php
/**
 * AuEligibilityTypeConstants
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Domainrobot JSON API
 *
 * Domainrobot JSON API for managing: Domains, SSL                                             Certificates, DNS and                                             much more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Domainrobot\Model;
use \Domainrobot\ObjectSerializer;

/**
 * AuEligibilityTypeConstants Class Doc Comment
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuEligibilityTypeConstants
{
    /**
     * Possible values of this enum
     */
    public const COMPANY = 'COMPANY';

    public const REGISTERED_BUSINESS = 'REGISTERED_BUSINESS';

    public const SOLE_TRADER = 'SOLE_TRADER';

    public const PARTNERSHIP = 'PARTNERSHIP';

    public const TRADEMARK_OWNER = 'TRADEMARK_OWNER';

    public const PENDING_TM_OWNER = 'PENDING_TM_OWNER';

    public const CITIZEN_RESIDENT = 'CITIZEN_RESIDENT';

    public const INCORPORATED_ASSOCIATION = 'INCORPORATED_ASSOCIATION';

    public const UNINCORPORATED_ASSOCIATION = 'UNINCORPORATED_ASSOCIATION';

    public const CLUB = 'CLUB';

    public const NON_PROFIT_ORGANISATION = 'NON_PROFIT_ORGANISATION';

    public const CHARITY = 'CHARITY';

    public const TRADE_UNION = 'TRADE_UNION';

    public const INDUSTRY_BODY = 'INDUSTRY_BODY';

    public const COMMERCIAL_STATUTORY_BODY = 'COMMERCIAL_STATUTORY_BODY';

    public const POLITICAL_PARTY = 'POLITICAL_PARTY';

    public const RELIGIOUS_CHURCH_GROUPS = 'RELIGIOUS_CHURCH_GROUPS';

    public const OTHER = 'OTHER';

    public const REGISTRABLE_BODY = 'REGISTRABLE_BODY';

    public const INDIGENOUS_CORPORATION = 'INDIGENOUS_CORPORATION';

    public const REGISTERED_ORGANISATION = 'REGISTERED_ORGANISATION';

    public const COOPERATIVE = 'COOPERATIVE';

    public const TRUST = 'TRUST';

    public const EDUCATIONAL_INSTITUTION = 'EDUCATIONAL_INSTITUTION';

    public const COMMONWEALTH_ENTITY = 'COMMONWEALTH_ENTITY';

    public const STATUTORY_BODY = 'STATUTORY_BODY';

    public const TRADING_COOPERATIVE = 'TRADING_COOPERATIVE';

    public const COMPANY_LIMITED_BY_GUARANTEE = 'COMPANY_LIMITED_BY_GUARANTEE';

    public const NON_DISTRIBUTING_COOPERATIVE = 'NON_DISTRIBUTING_COOPERATIVE';

    public const NON_TRADING_COOPERATIVE = 'NON_TRADING_COOPERATIVE';

    public const CHARITABLE_TRUST = 'CHARITABLE_TRUST';

    public const PUBLIC_PRIVATE_ANCILLARY_FUND = 'PUBLIC_PRIVATE_ANCILLARY_FUND';

    public const PEAK_STATE_TERRITORY_BODY = 'PEAK_STATE_TERRITORY_BODY';

    public const NOT_FOR_PROFIT_COMMUNITY_GROUP = 'NOT_FOR_PROFIT_COMMUNITY_GROUP';

    public const FOREIGN_EMBASSY_OR_CONSULATE = 'FOREIGN_EMBASSY_OR_CONSULATE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COMPANY,
            self::REGISTERED_BUSINESS,
            self::SOLE_TRADER,
            self::PARTNERSHIP,
            self::TRADEMARK_OWNER,
            self::PENDING_TM_OWNER,
            self::CITIZEN_RESIDENT,
            self::INCORPORATED_ASSOCIATION,
            self::UNINCORPORATED_ASSOCIATION,
            self::CLUB,
            self::NON_PROFIT_ORGANISATION,
            self::CHARITY,
            self::TRADE_UNION,
            self::INDUSTRY_BODY,
            self::COMMERCIAL_STATUTORY_BODY,
            self::POLITICAL_PARTY,
            self::RELIGIOUS_CHURCH_GROUPS,
            self::OTHER,
            self::REGISTRABLE_BODY,
            self::INDIGENOUS_CORPORATION,
            self::REGISTERED_ORGANISATION,
            self::COOPERATIVE,
            self::TRUST,
            self::EDUCATIONAL_INSTITUTION,
            self::COMMONWEALTH_ENTITY,
            self::STATUTORY_BODY,
            self::TRADING_COOPERATIVE,
            self::COMPANY_LIMITED_BY_GUARANTEE,
            self::NON_DISTRIBUTING_COOPERATIVE,
            self::NON_TRADING_COOPERATIVE,
            self::CHARITABLE_TRUST,
            self::PUBLIC_PRIVATE_ANCILLARY_FUND,
            self::PEAK_STATE_TERRITORY_BODY,
            self::NOT_FOR_PROFIT_COMMUNITY_GROUP,
            self::FOREIGN_EMBASSY_OR_CONSULATE
        ];
    }



    private function createData(string $variableName, mixed $data): mixed
    {
        $type = self::$openAPITypes[$variableName];
        preg_match("/([\\\\\w\d]+)(\[\])?/", $type, $matches);
        // handle object types
        if (count($matches) > 0 && count($matches) < 3) {
            try {
                if (!is_array($data)) {
                    return $data;
                }

                return (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($data);
            } catch (\Exception $e) {
                return $data;
            }
        } else if (count($matches) >= 3) {
            // Object[]
            // arrays of objects have to be handled differently
            $reflectionInstances = [];
            foreach ($data as $d) {
                try {
                    if (!is_array($d)) {
                        $reflectionInstances[] = $d;
                        continue;
                    }
                    $reflectionInstances[] = (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($d);
                } catch (\Exception $e) {
                    return $d;
                }
            }
            return $reflectionInstances;
        }

        return $data;
    }
}
