<?php
/**
 * EstimationParametersV1NameBased
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Service Pricer API
 *
 * The documentation for the internal price estimation API.<br> Every request expects the following headers:<ul><li>Content-Type: application/json</li><li>Accept: application/json</li></ul>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Domainrobot\Model;

use \ArrayAccess;
use \Domainrobot\ObjectSerializer;

/**
 * EstimationParametersV1NameBased Class Doc Comment
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EstimationParametersV1NameBased implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EstimationParametersV1_nameBased';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'pattern' => 'string',
        'segements' => 'string[]',
        'keywords' => 'string[]',
        'numWords' => 'string',
        'isIDN' => 'bool',
        'numDigits' => 'float',
        'numHyph' => 'float',
        'numChar' => 'float',
        'completelyNum' => 'float',
        'averageKeywordFrequency' => 'float',
        'averageKeywordPrice' => 'float',
        'averageLengthFrequency' => 'float',
        'averageLengthPrice' => 'float',
        'prefix' => 'string',
        'averagePrefixFrequency' => 'float',
        'averagePrefixPrice' => 'float',
        'suffix' => 'string',
        'averageSuffixFrequency' => 'float',
        'averageSuffixPrice' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'pattern' => null,
        'segements' => null,
        'keywords' => null,
        'numWords' => null,
        'isIDN' => null,
        'numDigits' => null,
        'numHyph' => null,
        'numChar' => null,
        'completelyNum' => null,
        'averageKeywordFrequency' => null,
        'averageKeywordPrice' => null,
        'averageLengthFrequency' => null,
        'averageLengthPrice' => null,
        'prefix' => null,
        'averagePrefixFrequency' => null,
        'averagePrefixPrice' => null,
        'suffix' => null,
        'averageSuffixFrequency' => null,
        'averageSuffixPrice' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'pattern' => false,
        'segements' => false,
        'keywords' => false,
        'numWords' => false,
        'isIDN' => false,
        'numDigits' => false,
        'numHyph' => false,
        'numChar' => false,
        'completelyNum' => false,
        'averageKeywordFrequency' => false,
        'averageKeywordPrice' => false,
        'averageLengthFrequency' => false,
        'averageLengthPrice' => false,
        'prefix' => false,
        'averagePrefixFrequency' => false,
        'averagePrefixPrice' => false,
        'suffix' => false,
        'averageSuffixFrequency' => false,
        'averageSuffixPrice' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'pattern' => 'pattern',
        'segements' => 'segements',
        'keywords' => 'keywords',
        'numWords' => 'numWords',
        'isIDN' => 'isIDN',
        'numDigits' => 'numDigits',
        'numHyph' => 'numHyph',
        'numChar' => 'numChar',
        'completelyNum' => 'completelyNum',
        'averageKeywordFrequency' => 'averageKeywordFrequency',
        'averageKeywordPrice' => 'averageKeywordPrice',
        'averageLengthFrequency' => 'averageLengthFrequency',
        'averageLengthPrice' => 'averageLengthPrice',
        'prefix' => 'prefix',
        'averagePrefixFrequency' => 'averagePrefixFrequency',
        'averagePrefixPrice' => 'averagePrefixPrice',
        'suffix' => 'suffix',
        'averageSuffixFrequency' => 'averageSuffixFrequency',
        'averageSuffixPrice' => 'averageSuffixPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'pattern' => 'setPattern',
        'segements' => 'setSegements',
        'keywords' => 'setKeywords',
        'numWords' => 'setNumWords',
        'isIDN' => 'setIsIDN',
        'numDigits' => 'setNumDigits',
        'numHyph' => 'setNumHyph',
        'numChar' => 'setNumChar',
        'completelyNum' => 'setCompletelyNum',
        'averageKeywordFrequency' => 'setAverageKeywordFrequency',
        'averageKeywordPrice' => 'setAverageKeywordPrice',
        'averageLengthFrequency' => 'setAverageLengthFrequency',
        'averageLengthPrice' => 'setAverageLengthPrice',
        'prefix' => 'setPrefix',
        'averagePrefixFrequency' => 'setAveragePrefixFrequency',
        'averagePrefixPrice' => 'setAveragePrefixPrice',
        'suffix' => 'setSuffix',
        'averageSuffixFrequency' => 'setAverageSuffixFrequency',
        'averageSuffixPrice' => 'setAverageSuffixPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'pattern' => 'getPattern',
        'segements' => 'getSegements',
        'keywords' => 'getKeywords',
        'numWords' => 'getNumWords',
        'isIDN' => 'getIsIDN',
        'numDigits' => 'getNumDigits',
        'numHyph' => 'getNumHyph',
        'numChar' => 'getNumChar',
        'completelyNum' => 'getCompletelyNum',
        'averageKeywordFrequency' => 'getAverageKeywordFrequency',
        'averageKeywordPrice' => 'getAverageKeywordPrice',
        'averageLengthFrequency' => 'getAverageLengthFrequency',
        'averageLengthPrice' => 'getAverageLengthPrice',
        'prefix' => 'getPrefix',
        'averagePrefixFrequency' => 'getAveragePrefixFrequency',
        'averagePrefixPrice' => 'getAveragePrefixPrice',
        'suffix' => 'getSuffix',
        'averageSuffixFrequency' => 'getAverageSuffixFrequency',
        'averageSuffixPrice' => 'getAverageSuffixPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('pattern', $data ?? [], null);
        $this->setIfExists('segements', $data ?? [], null);
        $this->setIfExists('keywords', $data ?? [], null);
        $this->setIfExists('numWords', $data ?? [], null);
        $this->setIfExists('isIDN', $data ?? [], null);
        $this->setIfExists('numDigits', $data ?? [], null);
        $this->setIfExists('numHyph', $data ?? [], null);
        $this->setIfExists('numChar', $data ?? [], null);
        $this->setIfExists('completelyNum', $data ?? [], null);
        $this->setIfExists('averageKeywordFrequency', $data ?? [], null);
        $this->setIfExists('averageKeywordPrice', $data ?? [], null);
        $this->setIfExists('averageLengthFrequency', $data ?? [], null);
        $this->setIfExists('averageLengthPrice', $data ?? [], null);
        $this->setIfExists('prefix', $data ?? [], null);
        $this->setIfExists('averagePrefixFrequency', $data ?? [], null);
        $this->setIfExists('averagePrefixPrice', $data ?? [], null);
        $this->setIfExists('suffix', $data ?? [], null);
        $this->setIfExists('averageSuffixFrequency', $data ?? [], null);
        $this->setIfExists('averageSuffixPrice', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = isset($fields[$variableName]) ? $this->createData($variableName, $fields[$variableName]) : $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets pattern
     *
     * @return string|null
     */
    public function getPattern()
    {
        return $this->container['pattern'];
    }

    /**
     * Sets pattern
     *
     * @param string|null $pattern pattern
     *
     * @return self
     */
    public function setPattern($pattern)
    {
        if (is_null($pattern)) {
            throw new \InvalidArgumentException('non-nullable pattern cannot be null');
        }
        $this->container['pattern'] = $pattern;

        return $this;
    }

    /**
     * Gets segements
     *
     * @return string[]|null
     */
    public function getSegements()
    {
        return $this->container['segements'];
    }

    /**
     * Sets segements
     *
     * @param string[]|null $segements segements
     *
     * @return self
     */
    public function setSegements($segements)
    {
        if (is_null($segements)) {
            throw new \InvalidArgumentException('non-nullable segements cannot be null');
        }
        $this->container['segements'] = $segements;

        return $this;
    }

    /**
     * Gets keywords
     *
     * @return string[]|null
     */
    public function getKeywords()
    {
        return $this->container['keywords'];
    }

    /**
     * Sets keywords
     *
     * @param string[]|null $keywords keywords
     *
     * @return self
     */
    public function setKeywords($keywords)
    {
        if (is_null($keywords)) {
            throw new \InvalidArgumentException('non-nullable keywords cannot be null');
        }
        $this->container['keywords'] = $keywords;

        return $this;
    }

    /**
     * Gets numWords
     *
     * @return string|null
     */
    public function getNumWords()
    {
        return $this->container['numWords'];
    }

    /**
     * Sets numWords
     *
     * @param string|null $numWords numWords
     *
     * @return self
     */
    public function setNumWords($numWords)
    {
        if (is_null($numWords)) {
            throw new \InvalidArgumentException('non-nullable numWords cannot be null');
        }
        $this->container['numWords'] = $numWords;

        return $this;
    }

    /**
     * Gets isIDN
     *
     * @return bool|null
     */
    public function getIsIDN()
    {
        return $this->container['isIDN'];
    }

    /**
     * Sets isIDN
     *
     * @param bool|null $isIDN isIDN
     *
     * @return self
     */
    public function setIsIDN($isIDN)
    {
        if (is_null($isIDN)) {
            throw new \InvalidArgumentException('non-nullable isIDN cannot be null');
        }
        $this->container['isIDN'] = $isIDN;

        return $this;
    }

    /**
     * Gets numDigits
     *
     * @return float|null
     */
    public function getNumDigits()
    {
        return $this->container['numDigits'];
    }

    /**
     * Sets numDigits
     *
     * @param float|null $numDigits numDigits
     *
     * @return self
     */
    public function setNumDigits($numDigits)
    {
        if (is_null($numDigits)) {
            throw new \InvalidArgumentException('non-nullable numDigits cannot be null');
        }
        $this->container['numDigits'] = $numDigits;

        return $this;
    }

    /**
     * Gets numHyph
     *
     * @return float|null
     */
    public function getNumHyph()
    {
        return $this->container['numHyph'];
    }

    /**
     * Sets numHyph
     *
     * @param float|null $numHyph numHyph
     *
     * @return self
     */
    public function setNumHyph($numHyph)
    {
        if (is_null($numHyph)) {
            throw new \InvalidArgumentException('non-nullable numHyph cannot be null');
        }
        $this->container['numHyph'] = $numHyph;

        return $this;
    }

    /**
     * Gets numChar
     *
     * @return float|null
     */
    public function getNumChar()
    {
        return $this->container['numChar'];
    }

    /**
     * Sets numChar
     *
     * @param float|null $numChar numChar
     *
     * @return self
     */
    public function setNumChar($numChar)
    {
        if (is_null($numChar)) {
            throw new \InvalidArgumentException('non-nullable numChar cannot be null');
        }
        $this->container['numChar'] = $numChar;

        return $this;
    }

    /**
     * Gets completelyNum
     *
     * @return float|null
     */
    public function getCompletelyNum()
    {
        return $this->container['completelyNum'];
    }

    /**
     * Sets completelyNum
     *
     * @param float|null $completelyNum completelyNum
     *
     * @return self
     */
    public function setCompletelyNum($completelyNum)
    {
        if (is_null($completelyNum)) {
            throw new \InvalidArgumentException('non-nullable completelyNum cannot be null');
        }
        $this->container['completelyNum'] = $completelyNum;

        return $this;
    }

    /**
     * Gets averageKeywordFrequency
     *
     * @return float|null
     */
    public function getAverageKeywordFrequency()
    {
        return $this->container['averageKeywordFrequency'];
    }

    /**
     * Sets averageKeywordFrequency
     *
     * @param float|null $averageKeywordFrequency averageKeywordFrequency
     *
     * @return self
     */
    public function setAverageKeywordFrequency($averageKeywordFrequency)
    {
        if (is_null($averageKeywordFrequency)) {
            throw new \InvalidArgumentException('non-nullable averageKeywordFrequency cannot be null');
        }
        $this->container['averageKeywordFrequency'] = $averageKeywordFrequency;

        return $this;
    }

    /**
     * Gets averageKeywordPrice
     *
     * @return float|null
     */
    public function getAverageKeywordPrice()
    {
        return $this->container['averageKeywordPrice'];
    }

    /**
     * Sets averageKeywordPrice
     *
     * @param float|null $averageKeywordPrice averageKeywordPrice
     *
     * @return self
     */
    public function setAverageKeywordPrice($averageKeywordPrice)
    {
        if (is_null($averageKeywordPrice)) {
            throw new \InvalidArgumentException('non-nullable averageKeywordPrice cannot be null');
        }
        $this->container['averageKeywordPrice'] = $averageKeywordPrice;

        return $this;
    }

    /**
     * Gets averageLengthFrequency
     *
     * @return float|null
     */
    public function getAverageLengthFrequency()
    {
        return $this->container['averageLengthFrequency'];
    }

    /**
     * Sets averageLengthFrequency
     *
     * @param float|null $averageLengthFrequency averageLengthFrequency
     *
     * @return self
     */
    public function setAverageLengthFrequency($averageLengthFrequency)
    {
        if (is_null($averageLengthFrequency)) {
            throw new \InvalidArgumentException('non-nullable averageLengthFrequency cannot be null');
        }
        $this->container['averageLengthFrequency'] = $averageLengthFrequency;

        return $this;
    }

    /**
     * Gets averageLengthPrice
     *
     * @return float|null
     */
    public function getAverageLengthPrice()
    {
        return $this->container['averageLengthPrice'];
    }

    /**
     * Sets averageLengthPrice
     *
     * @param float|null $averageLengthPrice averageLengthPrice
     *
     * @return self
     */
    public function setAverageLengthPrice($averageLengthPrice)
    {
        if (is_null($averageLengthPrice)) {
            throw new \InvalidArgumentException('non-nullable averageLengthPrice cannot be null');
        }
        $this->container['averageLengthPrice'] = $averageLengthPrice;

        return $this;
    }

    /**
     * Gets prefix
     *
     * @return string|null
     */
    public function getPrefix()
    {
        return $this->container['prefix'];
    }

    /**
     * Sets prefix
     *
     * @param string|null $prefix prefix
     *
     * @return self
     */
    public function setPrefix($prefix)
    {
        if (is_null($prefix)) {
            throw new \InvalidArgumentException('non-nullable prefix cannot be null');
        }
        $this->container['prefix'] = $prefix;

        return $this;
    }

    /**
     * Gets averagePrefixFrequency
     *
     * @return float|null
     */
    public function getAveragePrefixFrequency()
    {
        return $this->container['averagePrefixFrequency'];
    }

    /**
     * Sets averagePrefixFrequency
     *
     * @param float|null $averagePrefixFrequency averagePrefixFrequency
     *
     * @return self
     */
    public function setAveragePrefixFrequency($averagePrefixFrequency)
    {
        if (is_null($averagePrefixFrequency)) {
            throw new \InvalidArgumentException('non-nullable averagePrefixFrequency cannot be null');
        }
        $this->container['averagePrefixFrequency'] = $averagePrefixFrequency;

        return $this;
    }

    /**
     * Gets averagePrefixPrice
     *
     * @return float|null
     */
    public function getAveragePrefixPrice()
    {
        return $this->container['averagePrefixPrice'];
    }

    /**
     * Sets averagePrefixPrice
     *
     * @param float|null $averagePrefixPrice averagePrefixPrice
     *
     * @return self
     */
    public function setAveragePrefixPrice($averagePrefixPrice)
    {
        if (is_null($averagePrefixPrice)) {
            throw new \InvalidArgumentException('non-nullable averagePrefixPrice cannot be null');
        }
        $this->container['averagePrefixPrice'] = $averagePrefixPrice;

        return $this;
    }

    /**
     * Gets suffix
     *
     * @return string|null
     */
    public function getSuffix()
    {
        return $this->container['suffix'];
    }

    /**
     * Sets suffix
     *
     * @param string|null $suffix suffix
     *
     * @return self
     */
    public function setSuffix($suffix)
    {
        if (is_null($suffix)) {
            throw new \InvalidArgumentException('non-nullable suffix cannot be null');
        }
        $this->container['suffix'] = $suffix;

        return $this;
    }

    /**
     * Gets averageSuffixFrequency
     *
     * @return float|null
     */
    public function getAverageSuffixFrequency()
    {
        return $this->container['averageSuffixFrequency'];
    }

    /**
     * Sets averageSuffixFrequency
     *
     * @param float|null $averageSuffixFrequency averageSuffixFrequency
     *
     * @return self
     */
    public function setAverageSuffixFrequency($averageSuffixFrequency)
    {
        if (is_null($averageSuffixFrequency)) {
            throw new \InvalidArgumentException('non-nullable averageSuffixFrequency cannot be null');
        }
        $this->container['averageSuffixFrequency'] = $averageSuffixFrequency;

        return $this;
    }

    /**
     * Gets averageSuffixPrice
     *
     * @return float|null
     */
    public function getAverageSuffixPrice()
    {
        return $this->container['averageSuffixPrice'];
    }

    /**
     * Sets averageSuffixPrice
     *
     * @param float|null $averageSuffixPrice averageSuffixPrice
     *
     * @return self
     */
    public function setAverageSuffixPrice($averageSuffixPrice)
    {
        if (is_null($averageSuffixPrice)) {
            throw new \InvalidArgumentException('non-nullable averageSuffixPrice cannot be null');
        }
        $this->container['averageSuffixPrice'] = $averageSuffixPrice;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }



    private function createData(string $variableName, mixed $data): mixed
    {
        $type = self::$openAPITypes[$variableName];
        preg_match("/([\\\\\w\d]+)(\[\])?/", $type, $matches);
        // handle object types
        if (count($matches) > 0 && count($matches) < 3) {
            try {
                if (!is_array($data)) {
                    return $data;
                }

                return (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($data);
            } catch (\Exception $e) {
                return $data;
            }
        } else if (count($matches) >= 3) {
            // Object[]
            // arrays of objects have to be handled differently
            $reflectionInstances = [];
            foreach ($data as $d) {
                try {
                    if (!is_array($d)) {
                        $reflectionInstances[] = $d;
                        continue;
                    }
                    $reflectionInstances[] = (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($d);
                } catch (\Exception $e) {
                    return $d;
                }
            }
            return $reflectionInstances;
        }

        return $data;
    }
}
