<?php
/**
 * NameserverActionConstants
 *
 * PHP version 5
 *
 * @category Class
 * @package  IXDomainRobot
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domainrobot JSON API
 *
 * Domainrobot JSON API for managing: Domains, SSL            Certificates, DNS and            much more.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace IXDomainRobot\Model;
use \IXDomainRobot\ObjectSerializer;

/**
 * NameserverActionConstants Class Doc Comment
 *
 * @category Class
 * @package  IXDomainRobot
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NameserverActionConstants
{
    /**
     * Possible values of this enum
     */
    const PRIMARY = 'PRIMARY';
    const SECONDARY = 'SECONDARY';
    const COMPLETE = 'COMPLETE';
    const HIDDEN = 'HIDDEN';
    const NONE = 'NONE';
    const AUTO = 'AUTO';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRIMARY,
            self::SECONDARY,
            self::COMPLETE,
            self::HIDDEN,
            self::NONE,
            self::AUTO,
        ];
    }
}


