<?php
/**
 * TaskLimit
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Domainrobot JSON API
 *
 * Domainrobot JSON API for managing: Domains, SSL                                             Certificates, DNS and                                             much more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Domainrobot\Model;

use \ArrayAccess;
use \Domainrobot\ObjectSerializer;

/**
 * TaskLimit Class Doc Comment
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TaskLimit implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TaskLimit';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'created' => '\DateTime',
        'updated' => '\DateTime',
        'taskGroup' => '\Domainrobot\Model\TaskGroup',
        'limitSelf' => 'int',
        'inclusiveSelf' => 'int',
        'timeUnitSelf' => '\Domainrobot\Model\TimeUnitConstants',
        'limitChildren' => 'int',
        'inclusiveChildren' => 'int',
        'timeUnitChildren' => '\Domainrobot\Model\TimeUnitConstants',
        'count' => 'int',
        'user' => '\Domainrobot\Model\BasicUser'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'created' => 'date-time',
        'updated' => 'date-time',
        'taskGroup' => null,
        'limitSelf' => 'int32',
        'inclusiveSelf' => 'int32',
        'timeUnitSelf' => null,
        'limitChildren' => 'int32',
        'inclusiveChildren' => 'int32',
        'timeUnitChildren' => null,
        'count' => 'int32',
        'user' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'created' => false,
        'updated' => false,
        'taskGroup' => false,
        'limitSelf' => false,
        'inclusiveSelf' => false,
        'timeUnitSelf' => false,
        'limitChildren' => false,
        'inclusiveChildren' => false,
        'timeUnitChildren' => false,
        'count' => false,
        'user' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'created' => 'created',
        'updated' => 'updated',
        'taskGroup' => 'taskGroup',
        'limitSelf' => 'limitSelf',
        'inclusiveSelf' => 'inclusiveSelf',
        'timeUnitSelf' => 'timeUnitSelf',
        'limitChildren' => 'limitChildren',
        'inclusiveChildren' => 'inclusiveChildren',
        'timeUnitChildren' => 'timeUnitChildren',
        'count' => 'count',
        'user' => 'user'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'created' => 'setCreated',
        'updated' => 'setUpdated',
        'taskGroup' => 'setTaskGroup',
        'limitSelf' => 'setLimitSelf',
        'inclusiveSelf' => 'setInclusiveSelf',
        'timeUnitSelf' => 'setTimeUnitSelf',
        'limitChildren' => 'setLimitChildren',
        'inclusiveChildren' => 'setInclusiveChildren',
        'timeUnitChildren' => 'setTimeUnitChildren',
        'count' => 'setCount',
        'user' => 'setUser'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'created' => 'getCreated',
        'updated' => 'getUpdated',
        'taskGroup' => 'getTaskGroup',
        'limitSelf' => 'getLimitSelf',
        'inclusiveSelf' => 'getInclusiveSelf',
        'timeUnitSelf' => 'getTimeUnitSelf',
        'limitChildren' => 'getLimitChildren',
        'inclusiveChildren' => 'getInclusiveChildren',
        'timeUnitChildren' => 'getTimeUnitChildren',
        'count' => 'getCount',
        'user' => 'getUser'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
        $this->setIfExists('taskGroup', $data ?? [], null);
        $this->setIfExists('limitSelf', $data ?? [], null);
        $this->setIfExists('inclusiveSelf', $data ?? [], null);
        $this->setIfExists('timeUnitSelf', $data ?? [], null);
        $this->setIfExists('limitChildren', $data ?? [], null);
        $this->setIfExists('inclusiveChildren', $data ?? [], null);
        $this->setIfExists('timeUnitChildren', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = isset($fields[$variableName]) ? $this->createData($variableName, $fields[$variableName]) : $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets created
     *
     * @return \DateTime|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime|null $created Date of creation.
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return \DateTime|null
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param \DateTime|null $updated Date of the last update.
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets taskGroup
     *
     * @return \Domainrobot\Model\TaskGroup|null
     */
    public function getTaskGroup()
    {
        return $this->container['taskGroup'];
    }

    /**
     * Sets taskGroup
     *
     * @param \Domainrobot\Model\TaskGroup|null $taskGroup taskGroup
     *
     * @return self
     */
    public function setTaskGroup($taskGroup)
    {
        if (is_null($taskGroup)) {
            throw new \InvalidArgumentException('non-nullable taskGroup cannot be null');
        }
        $this->container['taskGroup'] = $taskGroup;

        return $this;
    }

    /**
     * Gets limitSelf
     *
     * @return int|null
     */
    public function getLimitSelf()
    {
        return $this->container['limitSelf'];
    }

    /**
     * Sets limitSelf
     *
     * @param int|null $limitSelf The self limit count
     *
     * @return self
     */
    public function setLimitSelf($limitSelf)
    {
        if (is_null($limitSelf)) {
            throw new \InvalidArgumentException('non-nullable limitSelf cannot be null');
        }
        $this->container['limitSelf'] = $limitSelf;

        return $this;
    }

    /**
     * Gets inclusiveSelf
     *
     * @return int|null
     */
    public function getInclusiveSelf()
    {
        return $this->container['inclusiveSelf'];
    }

    /**
     * Sets inclusiveSelf
     *
     * @param int|null $inclusiveSelf The self included count
     *
     * @return self
     */
    public function setInclusiveSelf($inclusiveSelf)
    {
        if (is_null($inclusiveSelf)) {
            throw new \InvalidArgumentException('non-nullable inclusiveSelf cannot be null');
        }
        $this->container['inclusiveSelf'] = $inclusiveSelf;

        return $this;
    }

    /**
     * Gets timeUnitSelf
     *
     * @return \Domainrobot\Model\TimeUnitConstants|null
     */
    public function getTimeUnitSelf()
    {
        return $this->container['timeUnitSelf'];
    }

    /**
     * Sets timeUnitSelf
     *
     * @param \Domainrobot\Model\TimeUnitConstants|null $timeUnitSelf timeUnitSelf
     *
     * @return self
     */
    public function setTimeUnitSelf($timeUnitSelf)
    {
        if (is_null($timeUnitSelf)) {
            throw new \InvalidArgumentException('non-nullable timeUnitSelf cannot be null');
        }
        $this->container['timeUnitSelf'] = $timeUnitSelf;

        return $this;
    }

    /**
     * Gets limitChildren
     *
     * @return int|null
     */
    public function getLimitChildren()
    {
        return $this->container['limitChildren'];
    }

    /**
     * Sets limitChildren
     *
     * @param int|null $limitChildren The limited count for each child
     *
     * @return self
     */
    public function setLimitChildren($limitChildren)
    {
        if (is_null($limitChildren)) {
            throw new \InvalidArgumentException('non-nullable limitChildren cannot be null');
        }
        $this->container['limitChildren'] = $limitChildren;

        return $this;
    }

    /**
     * Gets inclusiveChildren
     *
     * @return int|null
     */
    public function getInclusiveChildren()
    {
        return $this->container['inclusiveChildren'];
    }

    /**
     * Sets inclusiveChildren
     *
     * @param int|null $inclusiveChildren The included count for each child
     *
     * @return self
     */
    public function setInclusiveChildren($inclusiveChildren)
    {
        if (is_null($inclusiveChildren)) {
            throw new \InvalidArgumentException('non-nullable inclusiveChildren cannot be null');
        }
        $this->container['inclusiveChildren'] = $inclusiveChildren;

        return $this;
    }

    /**
     * Gets timeUnitChildren
     *
     * @return \Domainrobot\Model\TimeUnitConstants|null
     */
    public function getTimeUnitChildren()
    {
        return $this->container['timeUnitChildren'];
    }

    /**
     * Sets timeUnitChildren
     *
     * @param \Domainrobot\Model\TimeUnitConstants|null $timeUnitChildren timeUnitChildren
     *
     * @return self
     */
    public function setTimeUnitChildren($timeUnitChildren)
    {
        if (is_null($timeUnitChildren)) {
            throw new \InvalidArgumentException('non-nullable timeUnitChildren cannot be null');
        }
        $this->container['timeUnitChildren'] = $timeUnitChildren;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int|null $count The current count if available
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \Domainrobot\Model\BasicUser|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \Domainrobot\Model\BasicUser|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }



    private function createData(string $variableName, mixed $data): mixed
    {
        $type = self::$openAPITypes[$variableName];
        preg_match("/([\\\\\w\d]+)(\[\])?/", $type, $matches);
        // handle object types
        if (count($matches) > 0 && count($matches) < 3) {
            try {
                if (!is_array($data)) {
                    return $data;
                }

                return (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($data);
            } catch (\Exception $e) {
                return $data;
            }
        } else if (count($matches) >= 3) {
            // Object[]
            // arrays of objects have to be handled differently
            $reflectionInstances = [];
            foreach ($data as $d) {
                try {
                    if (!is_array($d)) {
                        $reflectionInstances[] = $d;
                        continue;
                    }
                    $reflectionInstances[] = (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($d);
                } catch (\Exception $e) {
                    return $d;
                }
            }
            return $reflectionInstances;
        }

        return $data;
    }
}
