<?php
/**
 * UserDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Domainrobot JSON API
 *
 * Domainrobot JSON API for managing: Domains, SSL                                             Certificates, DNS and                                             much more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Domainrobot\Model;

use \ArrayAccess;
use \Domainrobot\ObjectSerializer;

/**
 * UserDetails Class Doc Comment
 *
 * @category Class
 * @package  Domainrobot
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UserDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UserDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'organization' => 'string',
        'passwordResetMobile' => 'string',
        'passwordResetVerifyEmail' => 'string',
        'passwordResetEmail' => 'string',
        'fname' => 'string',
        'lname' => 'string',
        'phone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'organization' => null,
        'passwordResetMobile' => null,
        'passwordResetVerifyEmail' => null,
        'passwordResetEmail' => null,
        'fname' => null,
        'lname' => null,
        'phone' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'organization' => false,
        'passwordResetMobile' => false,
        'passwordResetVerifyEmail' => false,
        'passwordResetEmail' => false,
        'fname' => false,
        'lname' => false,
        'phone' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organization' => 'organization',
        'passwordResetMobile' => 'passwordResetMobile',
        'passwordResetVerifyEmail' => 'passwordResetVerifyEmail',
        'passwordResetEmail' => 'passwordResetEmail',
        'fname' => 'fname',
        'lname' => 'lname',
        'phone' => 'phone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organization' => 'setOrganization',
        'passwordResetMobile' => 'setPasswordResetMobile',
        'passwordResetVerifyEmail' => 'setPasswordResetVerifyEmail',
        'passwordResetEmail' => 'setPasswordResetEmail',
        'fname' => 'setFname',
        'lname' => 'setLname',
        'phone' => 'setPhone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organization' => 'getOrganization',
        'passwordResetMobile' => 'getPasswordResetMobile',
        'passwordResetVerifyEmail' => 'getPasswordResetVerifyEmail',
        'passwordResetEmail' => 'getPasswordResetEmail',
        'fname' => 'getFname',
        'lname' => 'getLname',
        'phone' => 'getPhone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('passwordResetMobile', $data ?? [], null);
        $this->setIfExists('passwordResetVerifyEmail', $data ?? [], null);
        $this->setIfExists('passwordResetEmail', $data ?? [], null);
        $this->setIfExists('fname', $data ?? [], null);
        $this->setIfExists('lname', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = isset($fields[$variableName]) ? $this->createData($variableName, $fields[$variableName]) : $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization The company name of the user.
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets passwordResetMobile
     *
     * @return string|null
     */
    public function getPasswordResetMobile()
    {
        return $this->container['passwordResetMobile'];
    }

    /**
     * Sets passwordResetMobile
     *
     * @param string|null $passwordResetMobile Mobile phone number to which the TAN is sent.
     *
     * @return self
     */
    public function setPasswordResetMobile($passwordResetMobile)
    {
        if (is_null($passwordResetMobile)) {
            throw new \InvalidArgumentException('non-nullable passwordResetMobile cannot be null');
        }
        $this->container['passwordResetMobile'] = $passwordResetMobile;

        return $this;
    }

    /**
     * Gets passwordResetVerifyEmail
     *
     * @return string|null
     */
    public function getPasswordResetVerifyEmail()
    {
        return $this->container['passwordResetVerifyEmail'];
    }

    /**
     * Sets passwordResetVerifyEmail
     *
     * @param string|null $passwordResetVerifyEmail Email address used for verification when resetting the password.
     *
     * @return self
     */
    public function setPasswordResetVerifyEmail($passwordResetVerifyEmail)
    {
        if (is_null($passwordResetVerifyEmail)) {
            throw new \InvalidArgumentException('non-nullable passwordResetVerifyEmail cannot be null');
        }
        $this->container['passwordResetVerifyEmail'] = $passwordResetVerifyEmail;

        return $this;
    }

    /**
     * Gets passwordResetEmail
     *
     * @return string|null
     */
    public function getPasswordResetEmail()
    {
        return $this->container['passwordResetEmail'];
    }

    /**
     * Sets passwordResetEmail
     *
     * @param string|null $passwordResetEmail Email address to which the TAN is sent.
     *
     * @return self
     */
    public function setPasswordResetEmail($passwordResetEmail)
    {
        if (is_null($passwordResetEmail)) {
            throw new \InvalidArgumentException('non-nullable passwordResetEmail cannot be null');
        }
        $this->container['passwordResetEmail'] = $passwordResetEmail;

        return $this;
    }

    /**
     * Gets fname
     *
     * @return string|null
     */
    public function getFname()
    {
        return $this->container['fname'];
    }

    /**
     * Sets fname
     *
     * @param string|null $fname The first name of the user.
     *
     * @return self
     */
    public function setFname($fname)
    {
        if (is_null($fname)) {
            throw new \InvalidArgumentException('non-nullable fname cannot be null');
        }
        $this->container['fname'] = $fname;

        return $this;
    }

    /**
     * Gets lname
     *
     * @return string|null
     */
    public function getLname()
    {
        return $this->container['lname'];
    }

    /**
     * Sets lname
     *
     * @param string|null $lname The last name of the user.
     *
     * @return self
     */
    public function setLname($lname)
    {
        if (is_null($lname)) {
            throw new \InvalidArgumentException('non-nullable lname cannot be null');
        }
        $this->container['lname'] = $lname;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone The phone number of the user.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }



    private function createData(string $variableName, mixed $data): mixed
    {
        $type = self::$openAPITypes[$variableName];
        preg_match("/([\\\\\w\d]+)(\[\])?/", $type, $matches);
        // handle object types
        if (count($matches) > 0 && count($matches) < 3) {
            try {
                if (!is_array($data)) {
                    return $data;
                }

                return (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($data);
            } catch (\Exception $e) {
                return $data;
            }
        } else if (count($matches) >= 3) {
            // Object[]
            // arrays of objects have to be handled differently
            $reflectionInstances = [];
            foreach ($data as $d) {
                try {
                    if (!is_array($d)) {
                        $reflectionInstances[] = $d;
                        continue;
                    }
                    $reflectionInstances[] = (new \ReflectionClass(str_replace('[]', '', $type)))->newInstance($d);
                } catch (\Exception $e) {
                    return $d;
                }
            }
            return $reflectionInstances;
        }

        return $data;
    }
}
